# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Limfjordssekretariatet_tools
                                 A QGIS plugin
 Limfjordssekretariatet forskellige tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Henrik Rosenskjold, 
                                Limfjordssekretariatet
        email                : henrik.rosenskjold@aalborg.dk
 ***************************************************************************/

"""
import os
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsApplication

# Initialize Qt resources from file resources.py
from .resources import *

from . import faelles_gui

# Import the code for the dialog
from .Limf_tools_dialog import Limfjordssekretariatet_toolsDialog


class Limfjordssekretariatet_tools:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
                      which provides the hook by which you can manipulate the QGIS application.
        :type iface: QgisInterface
        """
        self.iface = iface
        self.plugin_dir = None

        # Initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Initialize locale
        # Kan være usat i en frisk QGIS-profil; så ville [0:2] fejle på None
        # og pluginnet slet ikke blive indlæst.
        locale = (QSettings().value('locale/userLocale') or '')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Limfjordssekretariatet_tools_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.first_start = None
        self.tegne_action = None
        self.tegne_vaerktoej = None

    def tr(self, message):
        return QCoreApplication.translate('Limfjordssekretariatet_tools', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)

        # Menu og værktøjslinje deles med de øvrige Vandprojekter-plugins.
        if add_to_menu or add_to_toolbar:
            faelles_gui.tilfoej(self.iface, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icon inside QGIS."""
        # Filen frem for Qt-ressourcen: ressourcen ligger indbagt i
        # resources.py og ville stadig vise det gamle ikon.
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Vådområder …'),
            status_tip=self.tr(u'Værktøjer til vådområde- og '
                               u'lavbundsprojekter'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Tegneværktøjet får sin egen knap. Det kan ikke ligge bag den
        # modale dialog: man skal kunne tegne på kortet, mens knappen er
        # trykket ned, og den skal blive nede mellem to forløb.
        self.tegne_action = QAction(
            QgsApplication.getThemeIcon('/mActionCapturePolyline.svg'),
            self.tr(u'Tegn vandløbsforløb'),
            self.iface.mainWindow())
        self.tegne_action.setCheckable(True)
        self.tegne_action.setStatusTip(
            self.tr(u'Tegn et forløb ved at følge kanterne på de synlige lag'))
        self.tegne_action.setToolTip(self.tr(
            u'Tegn vandløbsforløb\n\n'
            u'Følger kanterne på de synlige linje- og fladelag. Klik for at '
            u'starte, før musen for at se forslaget, Enter eller højreklik '
            u'for at gemme. Backspace fortryder sidste punkt, Esc kasserer.'))
        self.tegne_action.triggered.connect(self.tegn_vandloebsforloeb)
        faelles_gui.tilfoej(self.iface, self.tegne_action)
        self.actions.append(self.tegne_action)

        self.first_start = True

    def tegn_vandloebsforloeb(self):
        """Slå tegneværktøjet til på kortet."""
        if self.tegne_vaerktoej is None:
            from .vandloebsforloeb import VandloebsforloebTool

            self.tegne_vaerktoej = VandloebsforloebTool(self.iface)
            # Uden dette bliver knappen hængende i trykket tilstand, når
            # brugeren skifter til et andet kortværktøj.
            self.tegne_vaerktoej.setAction(self.tegne_action)
        self.iface.mapCanvas().setMapTool(self.tegne_vaerktoej)

    def unload(self):
        """Removes the plugin menu item and icon."""
        # Kortværktøjet skal af kortet, før knappen forsvinder — ellers
        # sidder QGIS tilbage med et værktøj fra et plugin der ikke findes.
        if self.tegne_vaerktoej is not None:
            canvas = self.iface.mapCanvas()
            if canvas.mapTool() is self.tegne_vaerktoej:
                canvas.unsetMapTool(self.tegne_vaerktoej)
            self.tegne_vaerktoej.cleanup()
            self.tegne_vaerktoej = None

        for action in self.actions:
            faelles_gui.fjern(self.iface, action)
        self.actions = []
        self.tegne_action = None

    def run(self):
        """Run whenever user clicks icon/menu."""
        if self.first_start:
            self.first_start = False
            self.dlg = Limfjordssekretariatet_toolsDialog()

        self.dlg.show()
        self.dlg.exec_()
